# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-12 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publicaciones', '0002_auto_20170209_2136'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publicacion',
            managers=[
            ],
        ),
    ]
